config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  get '/:locale', to: "pages#home"

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    ActiveAdmin.routes(self)
    devise_for :users
    get '/infos-pratiques', to: "pages#infos_pratiques"
    get '/a-visiter', to: "pages#a_visiter"
    get '/rsvp', to: "pages#rsvp"
    get '/mentions-legales', to: "pages#mentions_legales"

    resources :guests, only: [:edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
class Guest < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  enum dinner_presence: { dinner_invited: 0, dinner_yes: 1, dinner_no: 2 }
  enum brunch_presence: { brunch_invited: 0, brunch_yes: 1, brunch_no: 2 }
  enum food_restriction: { no_restriction: 0, vegetarian: 1, pescetarian: 2, vegan: 3 }

  def self.ransackable_attributes(auth_object = nil)
    ["address", "brunch_presence", "child", "created_at", "dinner_presence", "email", "first_name", "food_restriction", "id", "id_value", "last_name", "phone", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["admin", "created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  before_action :authenticate_user!

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate_user!

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])
    @guest.update(guest_params)
    redirect_to rsvp_path, notice: "RSVP bien reçu(s), merci ❤️ !"
  end

  private

  def guest_params
    params.require(:guest).permit(:dinner_presence, :brunch_presence, :food_restriction)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def infos_pratiques
  end

  def a_visiter
  end

  def rsvp
    respond_to do |format|
      format.html
      format.turbo_stream { render turbo_stream: turbo_stream.append("guests-forms", partial: "guests/new_guest") }
    end
  end

  def mentions_legales
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/mariages_helper.rb
module MariagesHelper
end

app/views/guests/_new_guest.html.erb
<div class="mt-8" data-controller="search-guest" data-lenis-prevent>
  <%= simple_form_for rsvp_path do |form_search| %>
    <%= form_search.input :search, label: t('rsvp.form.search_label'), placeholder: t('rsvp.form.search_placeholder'), wrapper: :vertical_form_select, collection: Guest.all, label_method: :full_name, value_method: :id, input_html: { data: { search_guest_target: "input", action: "change->search-guest#search", controller: "tom-select" }} %>
  <% end %>
  <div class="mt-8">
    <%= turbo_frame_tag "edit_form", data: { search_guest_target: "editFrame" } do %>
    <% end %>
  </div>
</div>

app/views/guests/edit.html.erb
<h1>Modifier un invité</h1>

<%= turbo_frame_tag "edit_form_#{@guest.id}" do %>
  <p class="text-2xl mb-4">👋 <%= t('rsvp.form.hello1') %> <span class="font-bold"><%= @guest.first_name %></span><%= t('rsvp.form.hello2') %></p>
  <%= simple_form_for @guest, html: { data: { update_guests_target: "form", lenis_prevent: "" }} do |guest_form| %>
    <%= guest_form.input :dinner_presence, as: :radio_buttons, collection: [:dinner_yes, :dinner_no] %>
    <%= guest_form.input :brunch_presence, as: :radio_buttons, collection: [:brunch_yes, :brunch_no] %>
    <%= guest_form.input :food_restriction, as: :radio_buttons, collection: [:no_restriction, :vegetarian, :pescetarian] %>
  <% end %>

  <%= link_to rsvp_path, data: { turbo_stream: true}, class: "inline-flex gap-2 px-8 py-3 rounded border border-primary-600 text-primary-600 bg-tertiary-50 transition-colors hover:bg-tertiary-100" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
    </svg>
    <span><%= t('rsvp.form.new_guest_button') %></span>
  <% end %>
<% end %>

app/views/layouts/active_admin.html.erb
<!doctype html>
<html lang="<%= I18n.locale %>">
<head>
  <title><%= html_head_site_title %></title>
  <%= render "active_admin/html_head" %>
</head>
<body class="bg-white text-gray-950 antialiased">
  <%= render "active_admin/site_header", title: site_title %>
  <div class="xl:ms-60">
    <%= render "active_admin/main_navigation" %>
    <%= render "active_admin/page_header", title: @page_title || page_title %>
    <%= render "active_admin/flash_messages" %>
    <div data-test-page-content class="px-2.5 lg:px-5 grid grid-cols-1 gap-4 lg:gap-6 lg:grid-flow-col lg:auto-cols-[minmax(0,250px)]">
      <%= yield %>
      <%= render "active_admin/sidebar" %>
    </div>
    <%= render "active_admin/site_footer" %>
  </div>
</body>
</html>

app/views/layouts/active_admin_logged_out.html.erb
<!doctype html>
<html lang="<%= I18n.locale %>">
<head>
  <title><%= html_head_site_title %></title>
  <%= render "active_admin/html_head" %>
</head>
<body class="bg-gray-50 text-gray-950 antialiased">
  <div class="flex flex-col items-center justify-center min-h-screen py-4 sm:px-6 sm:py-8 mx-auto">
    <%= render "active_admin/flash_messages" %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mariage Stéphanie et Aimeric</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <main class="mt-8">
      <%= yield %>
      <%= render "shared/footer" %>
    </main>
    <script
      data-id-scroll
      data-autoinit="true"
      data-duration="1"
      data-orientation="vertical"
      data-smoothWheel="true"
      data-smoothTouch="false"
      data-touchMultiplier="1.5"
      data-easing="(t) => (t === 1 ? 1 : 1 - Math.pow(2, -10 * t))"
      data-useOverscroll="true"
      data-useControls="true"
      data-useAnchor="true"
      data-useRaf="true"
      data-infinite="false"
      defer
      src="https://cdn.prod.website-files.com/645e0e1ff7fdb6dc8c85f3a2/64a5544a813c7253b90f2f50_lenis-offbrand.txt">
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<section class="">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <%= image_tag "icone-ceremonie.svg", class: "mx-auto mb-4" %>
      <h2 class="text-2xl uppercase font-bold text-gray-800 md:text-3xl">
        <%= t("home.ceremony.title") %>
      </h2>
      <p class="mt-4 mb-8 max-w-2xl mx-auto text-gray-800 text-lg md:text-xl">
        <%= t("home.ceremony.description") %>
      </p>
      <div class="mt-4 mx-auto max-w-2xl grid grid-cols-[1fr_min-content_2fr] gap-4 items-center md:gap-16 md:grid-cols-[1fr_min-content_1fr]">
        <div class="justify-self-end">
          <p class="font-medium text-gray-600 text-xl md:text-3xl">14h30</p>
        </div>
        <div class="inline-block h-100 min-h-[1rem] w-px self-stretch bg-gray-500"></div>
        <%= link_to "https://maps.app.goo.gl/AiiifXHwdKRMW8ma8", target: "_blank", class: "decoration-gray-600 hover:underline" do %>
          <div class="justify-self-start text-left text-gray-600 text-lg md:text-xl">
            <p>Église Saint Martin</p>
            <p>24 Grand Rue</p>
            <p>33570 Montagne</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="bg-tertiary-50">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <%= image_tag "icone-cocktail.svg", class: "mx-auto mb-4" %>
      <h2 class="text-2xl uppercase font-bold text-gray-800 md:text-3xl">
        <%= t("home.cocktail.title") %>
      </h2>
      <p class="mt-4 mb-8 max-w-2xl mx-auto text-gray-800 text-lg md:text-xl">
        <%= t("home.cocktail.description") %>
      </p>
      <div class="mt-4 mx-auto max-w-2xl grid grid-cols-[1fr_min-content_2fr] gap-4 items-center md:gap-16 md:grid-cols-[1fr_min-content_1fr]">
        <div class="justify-self-end">
          <p class="font-medium text-gray-600 text-xl md:text-3xl">16h00</p>
        </div>
        <div class="inline-block h-100 min-h-[1rem] w-px self-stretch bg-gray-500"></div>
        <%= link_to "https://maps.app.goo.gl/zsWwEX8tTtD8crZn6", target: "_blank", class: "decoration-gray-600 hover:underline" do %>
          <div class="justify-self-start text-left text-gray-600 text-lg md:text-xl">
            <p>Château Saint Georges</p>
            <p>5 route de Saint Émilion</p>
            <p>33570 Montagne</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <%= image_tag "icone-diner.svg", class: "mx-auto mb-4" %>
      <h2 class="text-2xl uppercase font-bold text-gray-800 md:text-3xl">
        <%= t("home.dinner.title") %>
      </h2>
      <p class="mt-4 mb-8 max-w-2xl mx-auto text-gray-800 text-lg md:text-xl">
        <%= t("home.dinner.description") %>
      </p>
      <%= link_to rsvp_path, class: "group relative inline-block focus:outline-none" do %>
        <span class="absolute inset-0 translate-x-1.5 translate-y-1.5 rounded bg-primary-600 transition-transform group-hover:translate-x-0 group-hover:translate-y-0"></span>
        <span class="relative inline-block rounded px-8 py-3 font-bold uppercase tracking-widest text-white border-gold">
          <%= t("rsvp_button") %>
        </span>
      <% end %>
    </div>
  </div>
</section>

<section class="bg-tertiary-50">
  <div class="container mx-auto px-4 py-12">
    <div class="gap-8 md:gap-16 items-center mx-auto max-w-screen-xl lg:grid lg:grid-cols-2">
      <div class="text-center md:text-left">
        <%= image_tag "icone-brunch.svg", class: "mb-2 mx-auto" %>
        <h2 class="text-2xl uppercase font-bold text-gray-800 md:text-3xl">
          <%= t("home.brunch.title") %>
        </h2>
        <p class="mt-4 mb-8 max-w-2xl mx-auto text-gray-800 text-lg md:text-xl">
          <%= t("home.brunch.description") %>
        </p>
        <div class="mt-4 mb-8 mx-auto w-fit grid grid-cols-[min-content_min-content_min-content_min-content_max-content] gap-3 items-center md:gap-8">
          <div class="justify-self-end">
            <p class="text-gray-600 text-lg md:text-xl">Dim. 10/08/25</p>
          </div>
          <div class="inline-block h-100 min-h-[1rem] w-px self-stretch bg-gray-500"></div>
          <div class="">
            <p class="font-medium text-gray-600 text-xl md:text-3xl">10h00</p>
          </div>
          <div class="inline-block h-100 min-h-[1rem] w-px self-stretch bg-gray-500"></div>
          <%= link_to "https://maps.app.goo.gl/zsWwEX8tTtD8crZn6", target: "_blank", class: "decoration-gray-600 hover:underline" do %>
            <div class="justify-self-start text-left text-gray-600 text-md md:text-xl">
              <p>Château Saint Georges</p>
              <p>5 route de Saint Émilion</p>
              <p>33570 Montagne</p>
            </div>
          <% end %>
        </div>
        <%= link_to rsvp_path, class: "group relative inline-block focus:outline-none" do %>
          <span class="absolute inset-0 translate-x-1.5 translate-y-1.5 rounded bg-primary-600 transition-transform group-hover:translate-x-0 group-hover:translate-y-0"></span>
          <span class="relative inline-block rounded px-8 py-3 font-bold uppercase tracking-widest text-white border-gold">
            <%= t("rsvp_button") %>
          </span>
        <% end %>
      </div>
      <div class="grid grid-cols-2 gap-4 mt-8">
        <%= image_tag "breakfast.jpg", class: "w-full rounded-lg", alt: "Photo d'un petit déjeuner" %>
        <%= image_tag "birthday-cake.jpg", class: "mt-4 w-full lg:mt-10 rounded-lg", alt: "Photo d'un gâteau d'anniversaire" %>
      </div>
    </div>
  </div>
</section>

<section class="bg-secondary-400">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <%= image_tag "icone-cadeau.svg", class: "mx-auto mb-4" %>
      <p class="mt-4 max-w-5xl mx-auto text-white text-lg md:text-xl">
        <%= t("home.gift.description") %>
      </p>
    </div>
  </div>
</section>

<section class="">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <h2 class="text-2xl uppercase font-bold text-gray-800 md:text-3xl">
        <%= t("home.other.title") %>
      </h2>
      <p class="mt-4 mb-8 max-w-2xl mx-auto text-gray-800 text-lg md:text-xl">
        <%= t("home.other.description") %>
      </p>
      <div class="grid grid-cols-1 gap-8 mt-8 max-w-4xl mx-auto lg:grid-cols-2">
        <%= link_to infos_pratiques_path, class: "relative group flex flex-col justify-end overflow-hidden rounded px-8 pb-8 pt-40 w-full mx-auto" do %>
          <%= image_tag "wedding-car.jpg", alt: "Voiture de mariés", class: "absolute inset-0 h-full w-full object-cover transition-all group-hover:scale-110" %>
          <div class="absolute inset-0 bg-gradient-to-t from-gray-900 via-gray-900/40"></div>
          <h3 class="z-10 mt-3 text-3xl font-bold text-white"><%= t("home.other.infos.title") %></h3>
          <div class="z-10 gap-y-1 overflow-hidden text-lg text-gray-300"><%= t("home.other.infos.description") %></div>
        <% end %>
        <%= link_to infos_pratiques_path, class: "relative group flex flex-col justify-end overflow-hidden rounded px-8 pb-8 pt-40 w-full mx-auto" do %>
          <%= image_tag "saint-emilion.jpg", alt: "Saint-Emilion vu sur les toits et le clocher", class: "absolute inset-0 h-full w-full object-cover transition-all group-hover:scale-110" %>
          <div class="absolute inset-0 bg-gradient-to-t from-gray-900 via-gray-900/40"></div>
          <h3 class="z-10 mt-3 text-3xl font-bold text-white"><%= t("home.other.visit.title") %></h3>
          <div class="z-10 gap-y-1 overflow-hidden text-lg text-gray-300"><%= t("home.other.visit.description") %></div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="">
  <div class="container mx-auto px-4 py-12">
    <div class="text-center">
      <h2 class="text-4xl font-handwriting font-semibold lg:text-6xl">
        <%= t("home.end") %>
      </h2>
      </div>
    </div>
  </div>
</section>

app/views/pages/mentions_legales.html.erb
<h1>Pages#mentions_legales</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="mt-8 w-full text-white bg-secondary-400" data-controller="flash">
      <div class="container flex items-center justify-between px-6 py-4 mx-auto">
          <div class="flex">
              <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                  <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM21.6667 28.3333H18.3334V25H21.6667V28.3333ZM21.6667 21.6666H18.3334V11.6666H21.6667V21.6666Z">
                  </path>
              </svg>

              <p class="mx-3"><%= notice %></p>
          </div>

          <button class="p-1 transition-colors duration-300 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none" data-action="click->flash#remove">
              <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
          </button>
      </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-primary-600">
  <div class="relative mx-auto container px-4 py-8">
    <div class="fixed end-8 bottom-8">
      <a class="inline-block rounded-full bg-tertiary-50 p-2 text-white shadow-lg transition hover:bg-tertiary-100" href="#top">
        <span class="sr-only">Back to top</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="size-7 text-primary-600" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd"/>
        </svg>
      </a>
    </div>

    <div class="lg:flex lg:items-center lg:justify-between">
      <div>
        <div class="flex justify-center lg:justify-start">
          <%= image_tag "logo_blanc.svg", class: "w-12 h-12 md:w-20 md:h-20" %>
        </div>
      </div>

      <ul class="mt-8 flex flex-wrap justify-center gap-6 md:gap-8 lg:mt-0 lg:justify-end lg:gap-12">
        <li>
          <%= link_to t('footer.home'), root_path, class: "block py-2 px-3 no-underline text-white hover:text-gray-300 rounded md:p-0" %>
        </li>
        <li>
          <%= link_to t('footer.infos'), infos_pratiques_path, class: "block py-2 px-3 no-underline text-white hover:text-gray-300 rounded md:p-0" %>
        </li>
        <li>
          <%= link_to t('footer.to_visit'), a_visiter_path, class: "block py-2 px-3 no-underline text-white hover:text-gray-300 rounded md:p-0" %>
        </li>
      </ul>
    </div>

    <p class="mt-4 text-center text-sm text-gray-200 lg:text-right">
      Fait avec amour par Stéphanie et Aimeric.
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-transparent w-full z-20 absolute top-0 start-0" id="top" data-controller="navbar">
  <div class="container flex flex-wrap items-start justify-between mx-auto p-4">
    <%= link_to root_path, class: "flex items-center space-x-3 rtl:space-x-reverse" do %>
      <%= image_tag "logo_blanc.svg", class: "w-12 h-12 md:w-36 md:h-36", alt: "Logo site mariage" %>
    <% end %>
    <div class="flex gap-6">
      <div class="flex md:order-2 gap-6 rtl:space-x-reverse">
        <button type="button" class="z-50 inline-flex items-center p-2 w-10 h-10 justify-center text-gray-800 rounded md:hidden hover:bg-gray-100 focus:outline-none" data-action="click->navbar#openMenu">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky" data-navbar-target="menu">
        <ul class="min-h-screen md:min-h-max flex flex-col items-center p-4 pt-16 font-bold border border-gray-100 rounded bg-gray-50 space-y-4 md:space-y-0 md:space-x-8 md:flex-row md:p-0 md:mt-0 md:border-0 md:bg-transparent"
            data-controller="active-link">
          <li>
            <%= link_to t('navbar.home'), root_path, class: "block py-2 px-3 no-underline text-lg text-gray-800 hover:text-primary-600 md:p-0", data: { active_link_target: "link" } %>
          </li>
          <li>
            <div class="dropdown text-center relative transition-all transform">
              <%= link_to t('navbar.infos.link'), infos_pratiques_path, class: "block py-2 px-3 no-underline text-lg text-gray-800 hover:text-primary-600 md:p-0", data: { active_link_target: "link" } %>
              <div class="dropdown-content transition-all transform relative py-2 px-3 rounded md:absolute">
                <%= link_to t('navbar.infos.dropdown.bordeaux'), infos_pratiques_path(anchor: "bordeaux"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
                <%= link_to t('navbar.infos.dropdown.civil'), infos_pratiques_path(anchor: "mairie"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
                <%= link_to t('navbar.infos.dropdown.church'), infos_pratiques_path(anchor: "eglise"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
                <%= link_to t('navbar.infos.dropdown.diner'), infos_pratiques_path(anchor: "reception"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
                <%= link_to t('navbar.infos.dropdown.dress_code'), infos_pratiques_path(anchor: "dress-code"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
                <%= link_to t('navbar.infos.dropdown.accommodations'), infos_pratiques_path(anchor: "hebergement"), class: "block py-2 px-3 no-underline text-md font-normal text-gray-800 hover:text-primary-600 md:p-0", data: { action: "click->navbar#openMenu"} %>
              </div>
            </div>
          </li>
          <li>
            <%= link_to t('navbar.to_visit'), a_visiter_path, class: "block py-2 px-3 no-underline text-lg text-gray-800 hover:text-primary-600 md:p-0", data: { active_link_target: "link" } %>
          </li>
          <li>
            <%= render 'shared/locale_switch' %>
          </li>
          <li>
            <%= link_to rsvp_path, class: "group relative inline-block focus:outline-none" do %>
              <span class="absolute inset-0 translate-x-1.5 translate-y-1.5 rounded bg-primary-600 transition-transform group-hover:translate-x-0 group-hover:translate-y-0"></span>
              <span class="relative inline-block rounded px-8 py-3 font-bold uppercase tracking-widest text-white border-gold">
                <%= t("rsvp_button") %>
              </span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div class="w-full bg-cover h-32 md:h-72" style="background-image: url('<%= image_path('home-banner-background.webp') %>'); background-position: 100% 6%;">
    <div class="relative flex items-center justify-center w-full h-full bg-gray-800/10">
        <div class="container mx-auto mt-8 text-center flex justify-center md:justify-end">
            <div>
                <h1 class="text-4xl font-handwriting font-semibold lg:text-7xl">Stéphanie et Aimeric</h1>
                <p class="w-2/3 absolute mx-auto inset-x-0 bottom-[-27px] px-5 py-2 mt-2 text-2xl font-medium text-white capitalize transition-colors duration-300 transform bg-primary-600 rounded md:w-1/3 md:mt-4 md:text-4xl">
                  <span
                    data-controller="animated-number"
                    data-animated-number-start-value="0"
                    data-animated-number-end-value="09"
                    data-animated-number-duration-value="1000"></span>
                  <span> . </span>
                  <span
                    data-controller="animated-number"
                    data-animated-number-start-value="0"
                    data-animated-number-end-value="08"
                    data-animated-number-duration-value="1000"></span>
                  <span> . </span>
                  <span
                    data-controller="animated-number"
                    data-animated-number-start-value="2019"
                    data-animated-number-end-value="2025"
                    data-animated-number-duration-value="1000"></span>
                </p>
            </div>
        </div>
    </div>
</div>